### ISSUE TITLE
Build problem for Jetson Nano

### ISSUE THREAD

**Issue by Adamxu3d** [jetsonhacks/buildOpenCVTX1#3] opened 2019-04-08 18:52 UTC
Hi Jim I've been trying to install native OpenCV 3.4 onto the Jetson Nano module using your Jetson TX1 build repository with no luck. Every time I run into this 'no rule to make target 'usr/lib/aarch64-linux-gnu/libGL.so' problem, is there any way to solve this?  Also, does the python API utilise CUDA acceleration for OpenCV?  

Thx

Adam

**Comment by jetsonhacks** [comment] 2019-04-08 19:36
I know the answer to the second question. Currently python does not support CUDA acceleration in the 3.X series. I don't know if that has changed in 4.0.
Not sure as to what the problem is for the libGL.so issue. Does that file exist on your system?

Thanks for moving the issue here, it's really difficult to be coherent on YouTube about these matters.

**Comment by Adamxu3d** [comment] 2019-04-09 08:20
Thanks Jim, for the answer. I'm afraid that the libGL.so cannot be located under the designated directory for the freshly installed Jetpack 4.2, which rendered the libGL.so a broken link after the error showed up.

**Comment by jetsonhacks** [comment] 2019-04-09 16:42
Have you checked this on a freshly flashed Nano? When I check on my system, it is there. It could be that something overwrote/moved it when the dependencies were installed. Can you find it elsewhere on the system?

**Comment by jetsonhacks** [comment] 2019-04-10 04:22
Are you building anything else with this, such as opencv_contrib  ?

**Comment by ajkeeton** [comment] 2019-05-12 01:30
Just an FYI, I ran into this problem on my Nano. libgl.so was previously available, then at some point after installing a lot of various dependencies (including OpenCV), it was gone.

(fixed with sudo apt-get --reinstall install libglvnd-dev)

**Comment by raaka1** [comment] 2019-05-15 15:29
Yep I have a similar issue, sudo apt-get --reinstall install libglvnd-dev did not work for me i will retry

**Comment by derekclair** [comment] 2019-07-16 09:43
`sudo apt-get --reinstall install libglvnd-dev` did it for me too, thank you!

**Comment by omerfy** [comment] 2020-03-30 19:01
Hi, I have the same problem in may TX1 flashed with jetpack4.3. But I couldn't find any solution for this problem. I tried two recommend, and they didn't work. 
First one is  "sudo apt-get --reinstall install libglvnd-dev". Second one is the recommendation in the URL:  
- https://github.com/RobotLocomotion/drake/issues/2087

What do you think about the problem. Could anyone find a solution.

**Comment by omerfy** [comment] 2020-04-01 19:53
> Hi, I have the same problem in may TX1 flashed with jetpack4.3. But I couldn't find any solution for this problem. I tried two recommend, and they didn't work.
> First one is "sudo apt-get --reinstall install libglvnd-dev". Second one is the recommendation in the URL:
> 
> * [RobotLocomotion/drake#2087](https://github.com/RobotLocomotion/drake/issues/2087)
> 
> What do you think about the problem. Could anyone find a solution.

I reflashed my TX1 with Jetpack 4.2.3 and I changed the line "sudo ln -sf tegra/libGL.so libGL.so" in buildOpenCV.sh file as below:

- sudo ln -s /usr/lib/aarch64-linux-gnu/tegra/libGL.so /usr/lib/aarch64-linux-gnu/libGL.so
- sudo rm libGL.so 
- sudo ln -s libGL.so libGL.so.1

I think it is not about jetpack version and I don't know it is exactly true or not but it worked and built the OpenCV3.2.

Note: I used the buildOpenCV.sh file in order to build OpenCV3.2 changing the OPENCV_VERSION variable from 3.4.1 to 3.2.0

**Closed as completed** 2020-05-05 23:20 UTC

**Comment by BingXiong1995** [comment] 2020-05-11 17:51
sudo apt-get --reinstall install libglvnd-dev      solved this problem
